Iter13
mmskazak/shorturl pull request #13
Opened 2024-06-02 19:47 UTC by mmskazak

2024-06-07 18:39 UTC, s-shpak requested changes

2024-06-07 18:39 UTC, s-shpak commented on docker/docker-compose.yml
> +    image: postgres:13
Есть 16ая версия, используй ее

2024-06-07 18:39 UTC, s-shpak commented on internal/app/app.go
>  	zapLog *zap.SugaredLogger) *App {
```suggestion
	zapLog *zap.SugaredLogger,
) *App {
```

2024-06-07 18:39 UTC, s-shpak commented on go.mod
Опять надо обновить: см. здесь как настроить это для гит-хука https://app.pachca.com/chats/9180496?message=243787071

2024-06-07 18:39 UTC, s-shpak commented on internal/app/app.go
> +	handleSaveShortenURLsBatch := func(w http.ResponseWriter, r *http.Request) {
Я бы не создавал отдельную переменную здесь, а напрямую добавил анонимную функция в `router.Post`

2024-06-07 18:39 UTC, s-shpak commented on internal/app/app.go
> +			http.Error(w, ErrStartingServer, http.StatusInternalServerError)
Клиентам не надо возвращать никакую информацию при `InternalServerError`, так безопаснее

2024-06-07 18:39 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&config.DataBaseDSN, "d", config.DataBaseDSN, "Database connection string")
Это дефолтное значение же всегда будет "" ? Это правильно, но лучше явно прописать пустую строку как дефолтное значение

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/api/api.go
> +	storageInterface "mmskazak/shorturl/internal/storage"
Не вижу смысла переименовывать этот импорт

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/api/api.go
> +			http.Error(w, ServiceNotCanCreateShortURL, http.StatusInternalServerError)
См. коммент выше

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/api/api.go
> +	baseHost string) {
```suggestion
	baseHost string,
) {
```

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/api/api.go
> +		http.Error(w, fmt.Sprintf("error encoding response body: %v", err), http.StatusInternalServerError)
Отдавать пользователю причину нельзя, а залогировать `Internal Server Error` - надо

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/api/api.go
> +		http.Error(w, fmt.Sprintf("error write response body: %v", err), http.StatusInternalServerError)
--

2024-06-07 18:39 UTC, s-shpak commented on internal/handlers/web/web.go
> +			http.Error(w, "Что-то пошло не так!", http.StatusBadRequest)
Это не похоже на `Bad Request`

2024-06-07 18:39 UTC, s-shpak commented on internal/services/rwstorage/rwstorage.go
> +func (p *Producer) AppendToFile(sourceFilePath, destFilePath string) error {
А зачем копировать в новый файл ? Чтобы не потерять данные ?

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/factory/factory.go
> +	default:
У тебя дефолт и так `inmemory`, помести его кейс сюда

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/postrgresql.go
> +const ErrDatabaseUniqueViolation = "23505"
Лучше используй это: https://pkg.go.dev/github.com/jackc/pgerrcode

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/postrgresql.go
> +	conn *pgx.Conn
Используй пул соединений (pgx pool), смотри материалы к вебинару: https://github.com/s-shpak/yabinar-3.1-postgres

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/postrgresql.go
> +func (p *PostgreSQL) SetShortURL(ctx context.Context, shortURL string, targetURL string) error {
Эта функция делает несколкьо запросов к БД. Они должны быть обернуты в транзакцию

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/postrgresql.go
> +func (p *PostgreSQL) checkDuplicateOriginalURL(ctx context.Context, targetURL string) error {
Подумай, можно ли сделать по-другому (см. вебинар, приложение для генерации данных, там проверялась ошибка, кажется, что здесь можно так же)

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/savebatch.go
> +		if err != nil {
pgx делает управление коммитом-роллбеком проще, см. вебинар

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/savebatch.go
> +	batchSize := 4
как-то маловато, можно несколько тысяч

2024-06-07 18:39 UTC, s-shpak commented on internal/storage/postgresql/savebatch.go
> +	for start := 0; start < lenItems; start += batchSize {
См. pgx Batch: https://pkg.go.dev/github.com/jackc/pgx/v5#Batch

2024-06-08 14:18 UTC, mmskazak commented on go.mod
Добавил в lefthook
```
pre-commit:
  commands:
    lint:
      run: golangci-lint run -c .golangci.yml --fix
    go mod tidy:
      run: go mod tidy
```

2024-06-08 14:19 UTC, mmskazak commented on docker/docker-compose.yml
> +    image: postgres:13
обновил версию 
```
services:
  postgres:
    image: postgres:16.3
```

2024-06-08 14:23 UTC, mmskazak commented on internal/app/app.go
>  	zapLog *zap.SugaredLogger) *App {
обновил
```
	writeTimeout time.Duration,
	zapLog *zap.SugaredLogger,
) *App {
```

2024-06-08 14:40 UTC, mmskazak commented on internal/app/app.go
> +	handleSaveShortenURLsBatch := func(w http.ResponseWriter, r *http.Request) {
обновил
```
	router.Post("/api/shorten/batch", func(w http.ResponseWriter, r *http.Request) {
		api.SaveShortenURLsBatch(ctx, w, r, data, cfg.BaseHost)
	})
```

2024-06-08 14:42 UTC, mmskazak commented on internal/app/app.go
> +			http.Error(w, ErrStartingServer, http.StatusInternalServerError)
обновил
```
http.Error(w, "", http.StatusInternalServerError)
```

2024-06-09 07:35 UTC, mmskazak commented on internal/storage/postgresql/savebatch.go
> +	batchSize := 4
изменил
```
const batchSize = 1000
```

2024-06-09 07:36 UTC, mmskazak commented on internal/storage/postgresql/savebatch.go
> +	for start := 0; start < lenItems; start += batchSize {
переписал
```
for i := range lenItems {
		item := items[i]
		stmt := "INSERT INTO urls(short_url, original_url) VALUES ($1, $2) RETURNING short_url"
		batch.Queue(stmt, item.CorrelationID, item.OriginalURL)
```

2024-06-09 07:59 UTC, mmskazak commented on internal/storage/postgresql/savebatch.go
> +		if err != nil {
изменил
```
defer func() {
		if err = tx.Rollback(ctx); err != nil {
			if !errors.Is(err, sql.ErrTxDone) {
				log.Printf("error rollback transaction: %v", err)
			}
		}
	}()
```

2024-06-09 08:00 UTC, mmskazak commented on internal/storage/postgresql/postrgresql.go
> +func (p *PostgreSQL) checkDuplicateOriginalURL(ctx context.Context, targetURL string) error {
переделал
```
func (p *PostgreSQL) handleError(ctx context.Context, err error, targetURL string) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == ErrCodeDatabaseUniqueViolation {
		switch pgErr.ConstraintName {
		case "unique_short_url":
			return storageErrors.ErrKeyAlreadyExists
		case "unique_original_url":
			var shortURL string
			err := p.pool.QueryRow(ctx, "SELECT short_url FROM urls WHERE original_url = $1", targetURL).Scan(&shortURL)
			if err != nil {
				return fmt.Errorf("error recive short URL by original: %w", err)
			}
			return &storageErrors.ConflictError{
				ShortURL: shortURL,
				Err:      storageErrors.ErrOriginalURLAlreadyExists,
			}
		}
	}
	return fmt.Errorf("failed to insert record: %w", err)
}
```

2024-06-09 08:03 UTC, mmskazak commented on internal/storage/postgresql/postrgresql.go
> +func (p *PostgreSQL) SetShortURL(ctx context.Context, shortURL string, targetURL string) error {
обернул в транзакцию
```
func (p *PostgreSQL) SetShortURL(ctx context.Context, shortURL string, targetURL string) error {
	// Начало транзакции
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("error beginning transaction: %w", err)
	}

	defer func() {
		if errRollback := tx.Rollback(ctx); errRollback != nil {
			if !errors.Is(err, sql.ErrTxDone) {
				log.Printf("error rollback transaction: %v", errRollback)
			}
		}
	}()
```

2024-06-09 08:09 UTC, mmskazak commented on internal/config/config.go
> +	flag.StringVar(&config.DataBaseDSN, "d", config.DataBaseDSN, "Database connection string")
изменил
```
flag.StringVar(&config.DataBaseDSN, "d", "", "Database connection string")
```

2024-06-09 08:42 UTC, mmskazak commented on internal/handlers/api/api.go
> +	storageInterface "mmskazak/shorturl/internal/storage"
в одном месте будет конфликт имен, или это переименовывать или тогда аргумент storage
```
func SaveShortenURLsBatch(
	ctx context.Context,
	w http.ResponseWriter,
	r *http.Request,
	**storage** storageInterface.Storage,
	baseHost string) {
	// Парсинг JSON из тела запроса
	var requestData []**storageInterface**.Incoming
```

2024-06-09 08:47 UTC, mmskazak commented on internal/handlers/api/api.go
> +			http.Error(w, ServiceNotCanCreateShortURL, http.StatusInternalServerError)
поправил
```
http.Error(w, "", http.StatusInternalServerError)
```

2024-06-09 08:48 UTC, mmskazak commented on internal/handlers/api/api.go
> +	baseHost string) {
upd
```
	storage storageInterface.Storage,
	baseHost string,
) {
```

2024-06-09 10:25 UTC, mmskazak commented on internal/handlers/api/api.go
> +		http.Error(w, fmt.Sprintf("error write response body: %v", err), http.StatusInternalServerError)
upd
```
w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_, err = w.Write(responseData)
	if err != nil {
		http.Error(w, "", http.StatusInternalServerError)
		return
	}
```

2024-06-09 10:35 UTC, mmskazak commented on internal/handlers/web/web.go
> +			http.Error(w, "Что-то пошло не так!", http.StatusBadRequest)
upd
```
	_, err := w.Write([]byte(shortURL))
		if err != nil {
			log.Printf("Ошибка записи ответа w.Write([]byte(shortURL)) при конфликте original url %v", err)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}
```

2024-06-09 10:38 UTC, mmskazak commented on internal/services/rwstorage/rwstorage.go
> +func (p *Producer) AppendToFile(sourceFilePath, destFilePath string) error {
Мы пишем батчем в файл, если в процессе записи в файл у нас произойдет ошибка, надо как то откатить файл до начального сотояния, поэтому я сначала пишу батч в новый вайл, а когда записал, копирую его содержимое в конец основного фала, если же даже копирование упадет, я могу откатить и файл и мапу до сотояния до батча.

2024-06-09 10:44 UTC, mmskazak commented on internal/handlers/api/api.go
> +		http.Error(w, fmt.Sprintf("error encoding response body: %v", err), http.StatusInternalServerError)
upd
```
	responseData, err := json.Marshal(outputs)
	if err != nil {
		http.Error(w, "", http.StatusInternalServerError)
```

2024-06-09 10:51 UTC, mmskazak commented on internal/storage/factory/factory.go
> +	default:
По дефолту у нас файл если явно не указываетм путь до файла равным пустой строку, обновил
```
	switch {
	case cfg.DataBaseDSN != "":
		pg, err := postgresql.NewPostgreSQL(ctx, cfg)
		if err != nil {
			return nil, fmt.Errorf("failed to connect to postgresql: %w", err)
		}
		return pg, nil
	case cfg.FileStoragePath == "":
		sm, err := inmemory.NewInMemory()
		if err != nil {
			return nil, fmt.Errorf("failed to initialize an in-memory store: %w", err)
		}
		return sm, nil
	default:
		sf, err := infile.NewInFile(ctx, cfg)
		if err != nil {
			return nil, fmt.Errorf("failed to initialize an in-file store: %w", err)
		}
		return sf, nil
	}
```

2024-06-09 10:51 UTC, mmskazak commented on internal/storage/postgresql/postrgresql.go
> +	conn *pgx.Conn
переделал
```
type PostgreSQL struct {
	pool *pgxpool.Pool
}
```

2024-06-09 11:10 UTC, mmskazak commented on internal/storage/postgresql/postrgresql.go
> +const ErrDatabaseUniqueViolation = "23505"
upd
```
if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
```

2024-06-10 09:33 UTC, s-shpak commented on go.mod
Вообще говоря, это плохая идея: менять код каким-либо образом автоматически - плохая идея. Лучше посмотреть, надо ли апдейтить `go.mod` (то есть хук должен вернуть ошибку, если `go.mod` требует апдейта) и сделать его руками.

В треде в пачке описан именно этот подход. Тем не менее это необязтаельно, если ты не будешь это делать, то просто зарезолвь тред

2024-06-10 09:34 UTC, s-shpak commented on internal/handlers/api/api.go
> +	storageInterface "mmskazak/shorturl/internal/storage"
Лучше переименовать переменные

2024-06-10 09:40 UTC, s-shpak requested changes

2024-06-10 09:40 UTC, s-shpak commented on cmd/shortener/main.go
> +			log.Printf("Error closing storage: %v\n", err)
Почему не `zapLog`?

2024-06-10 09:40 UTC, s-shpak commented on internal/app/app.go
> +			log.Printf("The storage does not support Ping")
1. Не используй дефолтный логгер
2. Кажется, что это плохая идея: безобидный пинг к inmemory или файловому хранилищу может сразу возвращать `nil` не производя ошибку

2024-06-10 09:40 UTC, s-shpak commented on internal/storage/infile/infile.go
> +	log.Println("InFile storage closed (nothing to close currently)")
1. Надо использовать свой логгер
2. Это можно поместить на уровень `Debug`

2024-06-10 09:40 UTC, s-shpak commented on internal/storage/inmemory/inmemory.go
> +	"log"
--

2024-06-10 09:40 UTC, s-shpak commented on internal/storage/inmemory/inmemory.go
> +	log.Println("InMemory storage closed (nothing to close currently)")
--

2024-06-10 11:45 UTC, mmskazak commented on go.mod
```
pre-commit:
  commands:
    lint:
      run: golangci-lint run -c .golangci.yml --fix
    check go mod tidy:
      run: |
        export GO111MODULE=on
        go mod tidy || exit 1
        git diff --exit-code go.mod go.sum
      fail_on_non_zero_exit: true
      error_message: "go.mod or go.sum differs, please re-add it to your commit"
```

Такой вариант вроде бы тоже самое что и баш скрипт из пачки, и он подходит для любой ОС, так как я работаю на 2х ОС мне удобнее такой вариант. Понаблюдаю за тем как он работает.

2024-06-10 11:47 UTC, mmskazak commented on cmd/shortener/main.go
> +			log.Printf("Error closing storage: %v\n", err)
upd
```
defer func() {
		if err := storage.Close(); err != nil {
			zapLog.Infof("Error closing storage: %v\n", err)
		}
	}()
```

2024-06-10 11:56 UTC, mmskazak commented on internal/handlers/api/api.go
> +	storageInterface "mmskazak/shorturl/internal/storage"
переименовал
```
	"mmskazak/shorturl/internal/storage"
```

2024-06-10 11:58 UTC, mmskazak commented on internal/app/app.go
> +			log.Printf("The storage does not support Ping")
upd
```
	pingPostgreSQL := func(w http.ResponseWriter, r *http.Request) {
		pinger, ok := store.(Pinger)
		if !ok {
			zapLog.Infoln("The storage does not support Ping")
			return
		}
```

2024-06-10 12:06 UTC, mmskazak commented on internal/storage/infile/infile.go
> +	log.Println("InFile storage closed (nothing to close currently)")
я пробросил логгер через структуру
```
func (m *InFile) Close() error {
	// На данный момент закрывать нечего, но метод оставлен для возможных будущих изменений
	m.logger.Debugln("InFile storage closed (nothing to close currently)")
	return nil
}
```

```

func NewInFile(ctx context.Context, cfg *config.Config, logger zap.SugaredLogger) (*InFile, error) {
	inm, err := inmemory.NewInMemory()
	if err != nil {
		return nil, fmt.Errorf("error creating inmemory storage: %w", err)
	}

	ms := &InFile{
		inMe:     inm,
		filePath: cfg.FileStoragePath,
		logger:   logger,
	}
```

2024-06-10 12:38 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +	"log"
аналогично через структуру пробросил zap logger, стандартный логгер убрал

2024-06-10 12:38 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +	log.Println("InMemory storage closed (nothing to close currently)")
upd
```
func (m *InMemory) Close() error {
	// На данный момент закрывать нечего, но метод оставлен для возможных будущих изменений
	m.zapLog.Debugln("InMemory storage closed (nothing to close currently)")
	return nil
}

```

2024-06-10 13:12 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +	log.Println("InMemory storage closed (nothing to close currently)")
заменил во всех хранилищах стандартный логгер на zapLog

2024-06-10 16:57 UTC, s-shpak commented on cmd/shortener/main.go
> +			log.Printf("Error closing storage: %v\n", err)
Но это уже не уровень `Info`

2024-06-10 17:00 UTC, s-shpak requested changes

2024-06-10 17:00 UTC, s-shpak commented on internal/storage/factory/factory.go
> +		sm, err := inmemory.NewInMemory(zapLog)
Когда ты добавляешь логгер в какой-то компонент, можно использовать `With`, чтобы автоматически добавлять информацию о том, какой именно компонент записал лог

2024-06-10 19:43 UTC, mmskazak commented on internal/storage/factory/factory.go
> +		sm, err := inmemory.NewInMemory(zapLog)
upd
```
func NewStorage(ctx context.Context, cfg *config.Config, zapLog *zap.SugaredLogger) (storage.Storage, error) {
	switch {
	case cfg.DataBaseDSN != "":
		PostgreSQL := zapLog.With(zap.String("storage", "PostgreSQL"))
		pg, err := postgresql.NewPostgreSQL(ctx, cfg, PostgreSQL)
		if err != nil {
			return nil, fmt.Errorf("failed to connect to postgresql: %w", err)
		}
		return pg, nil
	case cfg.FileStoragePath == "":
		inMemoryLog := zapLog.With(zap.String("storage", "InMemory"))
		sm, err := inmemory.NewInMemory(inMemoryLog)
		if err != nil {
			return nil, fmt.Errorf("failed to initialize an in-memory store: %w", err)
		}
		return sm, nil
	default:
		InFile := zapLog.With(zap.String("storage", "InFile"))
		sf, err := infile.NewInFile(ctx, cfg, InFile)
		if err != nil {
			return nil, fmt.Errorf("failed to initialize an in-file store: %w", err)
		}
		return sf, nil
	}
}
```

2024-06-10 19:46 UTC, mmskazak commented on cmd/shortener/main.go
> +			log.Printf("Error closing storage: %v\n", err)
```
defer func() {
		if err := storage.Close(); err != nil {
			zapLog.Warn("Error closing storage: %v\n", err)
		}
	}()
```
выбирал между Warn и Error

2024-06-11 15:53 UTC, s-shpak requested changes

2024-06-11 15:53 UTC, s-shpak commented on internal/storage/factory/factory.go
> +		PostgreSQL := zapLog.With(zap.String("storage", "PostgreSQL"))
Локальные переменные в Go не называют с большой буквы

2024-06-11 15:53 UTC, s-shpak commented on lefthook.yml
> -      run: |
Ты решил откатиться на прежнюю работу с `go mod tidy` ?

2024-06-14 11:46 UTC, s-shpak approved these changes

2024-06-30 13:56 UTC, merged