Iter15
mmskazak/shorturl pull request #15
Opened 2024-06-19 19:35 UTC by mmskazak

2024-06-25 15:34 UTC, s-shpak requested changes

2024-06-25 15:34 UTC, s-shpak commented on docker/docker-compose.yml
Зачем тебе docker compose, если в Makefile ты запускаешь DB просто через докер ? Лучше выбери либо то, либо то

2024-06-25 15:34 UTC, s-shpak commented on internal/ctxkeys/ctx_keys.go
> +	// ...
deadcode

2024-06-25 15:34 UTC, s-shpak commented on internal/handlers/api/api.go
> +			log.Printf("Ошибка buildJSONResponse: %v", err)
Не используй пакет `log`, используй свой кастомный логгер

2024-06-25 15:34 UTC, s-shpak commented on internal/handlers/api/delete_user_urls.go
> +	log.Printf("Received request to delete URLs: %v", urlIDs)
--

2024-06-25 15:34 UTC, s-shpak commented on internal/handlers/api/delete_user_urls.go
> +		log.Printf("Error deleting URLs: %v", err)
Если здесь возникла ошибка, то ее надо обработать (вернутьь пользователю статус)

2024-06-25 15:34 UTC, s-shpak commented on internal/middleware/auth.go
> +func getSignedCookie(r *http.Request, name, key string) (string, bool) {
Возвращай кастомные ошибки, а не bool

2024-06-25 15:34 UTC, s-shpak commented on internal/middleware/auth.go
> +func setSignedCookie(w http.ResponseWriter, name, value, key string) {
Используй JWT для куки

2024-06-25 15:34 UTC, s-shpak commented on internal/middleware/auth.go
> +			if uri == "/api/user/urls" {
Обсудили на 1-1

2024-06-25 15:34 UTC, s-shpak commented on internal/storage/postgresql/delete_urls.go
> +		log.Printf("Failed to begin transaction: %v", err)
Логировать здесь не надо

2024-06-25 15:34 UTC, s-shpak commented on internal/storage/postgresql/delete_urls.go
> +			if !errors.Is(err, sql.ErrTxDone) {
Тебе не нужна эта проверка, см. документацию к Rollback

2024-06-25 15:34 UTC, s-shpak commented on internal/storage/postgresql/delete_urls.go
> +		batch.Queue("UPDATE urls SET deleted = TRUE WHERE short_url = $1", shortURL)
В какой-то момент должно происходить реальное (жесткое) удаление этих записей. Для асинхронности используй компонент, который выполняется в отдельной горутине

2024-06-25 15:34 UTC, s-shpak commented on internal/storage/postgresql/set_shorturl.go
> +	_, err = tx.Exec(ctx, `
Если запись, которая помечена как удаленная, приводит к коллизии, то это неверное поведение, коллизии быть не должно

2024-06-25 15:34 UTC, s-shpak commented on internal/handlers/api/user_urls.go
> +	userID, ok := r.Context().Value(ctxkeys.KeyUserID).(string)
А что если значения с ключом `KeyUserID` не будет в контексте ?

2024-06-25 15:47 UTC, mmskazak commented on docker/docker-compose.yml
удалил docker compose

2024-06-25 15:49 UTC, mmskazak commented on internal/ctxkeys/ctx_keys.go
> +	// ...
```// ... -

2024-06-25 15:51 UTC, mmskazak commented on internal/ctxkeys/ctx_keys.go
> +	// ...
KeyUserID - используется в 5 местах, как значение ключа для контекста через корый передаю user_id

2024-06-25 17:14 UTC, mmskazak commented on internal/handlers/api/api.go
> +			log.Printf("Ошибка buildJSONResponse: %v", err)
заменил на свой логгер

2024-06-25 17:15 UTC, mmskazak commented on internal/handlers/api/delete_user_urls.go
> +	log.Printf("Received request to delete URLs: %v", urlIDs)
заменил на свой логер

2024-06-25 17:23 UTC, mmskazak commented on internal/handlers/api/delete_user_urls.go
> +		log.Printf("Error deleting URLs: %v", err)
upd
```
if err != nil {
		zapLog.Errorf("Error deleting URLs: %v", err)
		http.Error(w, "", http.StatusInternalServerError)
	}
```

2024-06-25 18:15 UTC, mmskazak commented on internal/storage/postgresql/delete_urls.go
> +		log.Printf("Failed to begin transaction: %v", err)
upd
```
if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
```

2024-06-25 18:17 UTC, mmskazak commented on internal/storage/postgresql/delete_urls.go
> +			if !errors.Is(err, sql.ErrTxDone) {
upd
```
if err := tx.Rollback(ctx); err != nil {
			s.zapLog.Errorf("Error rollback transaction: %v", err)
		}
```

2024-06-25 18:22 UTC, mmskazak commented on internal/handlers/api/user_urls.go
> +	userID, ok := r.Context().Value(ctxkeys.KeyUserID).(string)
дальше идет проверка, если значение отсутствует, возвращаем 401 ошибку
```
// Получаем userID из контекста
	userID, ok := r.Context().Value(ctxkeys.KeyUserID).(string)
	if !ok {
		// Если userID не найден или неверного типа, возвращаем ошибку
		zapLog.Error("Не удалось получить id пользователя")
		http.Error(w, "", http.StatusUnauthorized)
		return
	}
```

2024-06-29 07:19 UTC, mmskazak commented on internal/handlers/api/user_urls.go
> +	userID, ok := r.Context().Value(ctxkeys.KeyUserID).(string)
Сделал проверку на существование ключа userID, и перестали проходить автотесты, добавил еще один мидлвар, как в первом варианте, который проверяет отдельный endpoint на наличие JWT, и елси его нет или он не валиден, то тогда возвращаем 401.
```
func GetUserURLsForAuth(next http.Handler, cfg *config.Config) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		secretKey := cfg.SecretKey
		_, err := getSignedPayloadJWT(r, authorizationCookieName, secretKey)
		if err != nil && r.URL.Path == "/api/user/urls" {
			w.WriteHeader(http.StatusUnauthorized)
		}
		// Передаем запрос следующему обработчику
		next.ServeHTTP(w, r)
	})
}
```

2024-06-29 07:25 UTC, mmskazak commented on internal/handlers/api/user_urls.go
> +	userID, ok := r.Context().Value(ctxkeys.KeyUserID).(string)
upd 
 так как теперь в подписанном cookie JWT, логика стала такой
 	```
// Получаем userID из контекста
	payload, ok := r.Context().Value(ctxkeys.PayLoad).(jwtbuilder.PayloadJWT)
	userID := payload.UserID
	zapLog.Infof("FindUserURLs - UserID: %v", userID)
	if !ok {
		// Если userID не найден или неверного типа, возвращаем ошибку
		zapLog.Error("Не удалось получить id пользователя")
		http.Error(w, "", http.StatusUnauthorized)
		return
	}

```

2024-06-29 07:46 UTC, mmskazak commented on internal/storage/postgresql/set_shorturl.go
> +	_, err = tx.Exec(ctx, `
upd
```
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS urls(
                                         id SERIAL PRIMARY KEY,
                                         short_url VARCHAR(255) NOT NULL,
                                         original_url TEXT NOT NULL,
                                         user_id VARCHAR(255) NOT NULL,
                                         deleted BOOLEAN default FALSE
);

CREATE UNIQUE INDEX unique_original_url ON urls (original_url) WHERE deleted = FALSE;
CREATE UNIQUE INDEX unique_short_url ON urls (short_url) WHERE deleted = FALSE;

COMMIT;
```

2024-06-29 07:47 UTC, mmskazak commented on internal/middleware/auth.go
> +func getSignedCookie(r *http.Request, name, key string) (string, bool) {
upd
```
func getSignedPayloadJWT(r *http.Request, name, secretKey string) (string, error) {
```

2024-06-29 07:49 UTC, mmskazak commented on internal/middleware/auth.go
> +func setSignedCookie(w http.ResponseWriter, name, value, key string) {
upd
```
func setSignedCookie(w http.ResponseWriter, name string, token string) {
```

2024-06-29 07:53 UTC, mmskazak commented on internal/middleware/auth.go
> +			if uri == "/api/user/urls" {
Обновил логику, но автотесты перестали проходить, оставил новую логику в новом мидлваре проверяющем существование userID, а так же добавил старую логику проверяющую наличие токена на endpoint и все заработало.

2024-06-29 07:55 UTC, mmskazak commented on internal/ctxkeys/ctx_keys.go
> +	// ...
upd теперь такой ключ для контекста
```
const (
	PayLoad key = iota
)
```

2024-06-30 11:46 UTC, s-shpak approved these changes

2024-06-30 13:56 UTC, merged