Iter20
mmskazak/shorturl pull request #21
Opened 2024-08-29 09:56 UTC by mmskazak

2024-09-03 09:31 UTC, s-shpak requested changes

2024-09-03 09:31 UTC, s-shpak commented on cmd/staticlint/noosexit/noosexit.go
> +				if ok {
Я бы уменьшил здесь уровень вложенности

2024-09-03 09:31 UTC, s-shpak commented on cmd/version/main.go
> +			log.Println("Error closing file version.go")
Оригинальную ошибку также надо логировать

2024-09-03 09:31 UTC, s-shpak commented on cmd/version/main.go
> +		fmt.Println("Error writing to file:", err)
Функции `fmt.Print*` использовать нельзя

2024-09-03 09:33 UTC, s-shpak requested changes

2024-09-03 09:33 UTC, s-shpak commented on cmd/shortener/version_gen.go
> +	BuildVersion = "N/A"
Зачем экспортировать эти переменные ?

2024-09-03 12:07 UTC, mmskazak commented on cmd/shortener/version_gen.go
> +	BuildVersion = "N/A"
upd
```
// Build параметры компиляции программы.
var (
	buildVersion = "N/A"
	buildDate    = "N/A"
	buildCommit  = "N/A"
)
```

2024-09-03 12:15 UTC, mmskazak commented on cmd/version/main.go
> +		fmt.Println("Error writing to file:", err)
upd
```
_, err = file.WriteString(code)
	if err != nil {
		log.Printf("Error writing to file: %v \n", err)
	}
```

2024-09-03 12:18 UTC, mmskazak commented on cmd/version/main.go
> +			log.Println("Error closing file version.go")
upd
```
defer func(file *os.File) {
		err := file.Close()
		if err != nil {
			log.Printf("Error closing file version.go: %v \n", err)
		}
	}(file)
```

2024-09-03 12:24 UTC, mmskazak commented on cmd/staticlint/noosexit/noosexit.go
> +				if ok {
upd
```
	// Проверяем что это вызов os. Exit
				if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
					ident, ok := sel.X.(*ast.Ident)
					if ok && ident.Name == "os" && sel.Sel.Name == "Exit" {
						pass.Reportf(call.Pos(), "direct call to os.Exit is not allowed in main package")
					}
				}
```

2024-09-07 09:53 UTC, s-shpak approved these changes

2024-09-07 13:07 UTC, merged