Iter25
mmskazak/shorturl pull request #26
Opened 2024-09-28 13:42 UTC by mmskazak

2024-10-03 09:57 UTC, s-shpak commented on internal/app/register_grpc.go
> +	sh.zapLog.Infoln("GRPC SaveShortenURLsBatch called")
Такие сообщения лучше перенести на уровень Debug

2024-10-03 10:08 UTC, s-shpak requested changes

2024-10-03 10:08 UTC, s-shpak commented on internal/proto/shorturl.proto
> +syntax = "proto3";
Посмотри видео вебинара: в целом, критических ошибок нет, но попробуй разобраться, как лучше писать proto-файлы. Например:
- разбить на файлы
- проставить лучшее значение в `go_package`
- не использовать примитивные значения в `Request`/`Response`
- не использовать `optional`

2024-10-03 10:08 UTC, s-shpak commented on internal/services/jwttoken/jwttoken.go
> +	parts := strings.Split(jwt, ".")
А почему бы не использовать библиотеку типа https://pkg.go.dev/github.com/golang-jwt/jwt для таких проверок ?

2024-10-03 10:08 UTC, s-shpak commented on internal/app/register_grpc.go
> +	sh.zapLog.Infoln("GRPC FindUserURLs called")
Такие сообщения лучше перенести на уровень debug

2024-10-04 06:17 UTC, mmskazak commented on internal/app/register_grpc.go
> +	sh.zapLog.Infoln("GRPC FindUserURLs called")
```
func (sh *ShortURLService) FindUserURLs(
	ctx context.Context,
	in *proto.FindUserURLsRequest,
) (*proto.FindUserURLsResponse, error) {
	sh.zapLog.Debugln("GRPC FindUserURLs called")
	var response proto.FindUserURLsResponse

```

2024-10-04 10:29 UTC, mmskazak commented on internal/services/jwttoken/jwttoken.go
> +	parts := strings.Split(jwt, ".")
заюзал
```
// GetSignedPayloadJWT извлекает и проверяет подписанную полезную нагрузку JWT из cookie.
func GetSignedPayloadJWT(tokenString string, secretKey string) (string, error) {
	token, err := jwtGolang.ParseWithClaims(tokenString, &jwtbuilder.PayloadJWT{}, func(token *jwtGolang.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwtGolang.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(secretKey), nil
	})
	if err != nil {
		return "", fmt.Errorf("error GetSignedPayloadJWT: %w", err)
	}

	data, err := json.Marshal(token.Claims)
	if err != nil {
		return "", fmt.Errorf("error marshalling token claims: %w", err)
	}

	return string(data), nil
}
```

2024-10-05 16:03 UTC, mmskazak commented on internal/proto/shorturl.proto
> +syntax = "proto3";
Вебинар посмотрел,
```go_package``` изменил,
proto файл разбил на на несколько логически обособленных,
примитиные значения убрал, все обернул в свои структуры,
```optional``` убрал

2024-10-08 09:43 UTC, s-shpak approved these changes

2024-11-24 11:57 UTC, merged