Iter5
mmskazak/shorturl pull request #5
Opened 2024-04-28 12:59 UTC by mmskazak

2024-05-05 12:34 UTC, s-shpak requested changes

2024-05-05 12:34 UTC, s-shpak commented on internal/app/helpers/appinfo.go
> +func GetAppNameAndVersion() AppInfo {
Лучше вернуть `bool` или `error`, чтобы указать, что информация не доступна

2024-05-05 12:34 UTC, s-shpak commented on internal/app/helpers/appinfo.go
> +	if app.name == "" {
См. комментарий к сигнатуре

2024-05-05 12:34 UTC, s-shpak commented on cmd/shortener/main.go
> +const readTimeout = 10 * time.Second
Это стоит тоже убрать в конфиг

2024-05-05 12:34 UTC, s-shpak commented on cmd/shortener/main_test.go
> +func TestMainPage_Get_Greeting(t *testing.T) {
А зачем этот тест помещать в `main`? кажется, что это проверка роутера, лучше поместить тест рядом с ним

2024-05-05 12:34 UTC, s-shpak commented on internal/app/config/config.go
> +type IConfig interface {
Интерфейсы в Go объявляются там, где они используются

2024-05-05 12:34 UTC, s-shpak commented on internal/app/config/config.go
> +	GetAddress() string
В Go использование геттеров и сеттеров не принято. Из этого кажется, что этот интерфейс не нужен

2024-05-05 12:34 UTC, s-shpak commented on internal/app/config/config.go
> +	if envServAddr := os.Getenv("SERVER_ADDRESS"); envServAddr != "" {
Лучше использовать https://pkg.go.dev/os#LookupEnv

2024-05-05 12:34 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&config.address, "a", config.GetAddress(), "Устанавливаем ip адрес нашего сервера.")
```suggestion
	flag.StringVar(&config.address, "a", config.GetAddress(), "IP-адерс сервера")
```

2024-05-05 12:34 UTC, s-shpak commented on internal/pkg/shorturl/shorturl.go
> +package shorturl
Почему ты решил этот код поместить в директорию `internal/pkg` ?

2024-05-05 12:34 UTC, s-shpak commented on internal/pkg/shorturl/shorturl.go
> +	ms := mapstorage.NewMapStorage()
Здесь лучше использовать DI: передай хранилище извне

2024-05-05 12:34 UTC, s-shpak commented on internal/pkg/shorturl/shorturl.go
> +	log.Println("Server is running on " + a.server.Addr)
```suggestion
	log.Printf(...)
```

2024-05-05 12:34 UTC, s-shpak commented on internal/pkg/shorturl/shorturl.go
> +		log.Println("Error starting server:", err)
А если ошибка от того, что сервер завершился нормально ?

2024-05-05 12:34 UTC, s-shpak commented on internal/pkg/shorturl/shorturl_test.go
> +	t.Skip()
Почему ? Если тест не работает, то его надо либо исправить, либо убрать

2024-05-05 12:34 UTC, s-shpak commented on internal/app/helpers/helpers.go
> +			panic(err) // Обрабатываем ошибку, если не удается сгенерировать случайное число
Паники не нужны

2024-05-05 12:34 UTC, s-shpak commented on internal/app/helpers/helpers.go
> +	"crypto/rand"
Проще использовать `math/rand`

2024-05-05 12:34 UTC, s-shpak commented on internal/app/helpers/helpers_test.go
> +	tests := []struct {
А если переданный аргумент `-1` или `0`?

2024-05-05 12:34 UTC, s-shpak commented on internal/app/handlers/handles.go
> +	shortedURL := baseHost + "/" + id
Лучше исползовать https://pkg.go.dev/net/url#JoinPath

2024-05-05 12:34 UTC, s-shpak commented on internal/app/handlers/handles.go
> +		return
Какой ответ возвращается пользователю ?

2024-05-05 12:34 UTC, s-shpak commented on internal/app/handlers/handles.go
> +func CreateShortURL(w http.ResponseWriter, r *http.Request, data *mapstorage.MapStorage, baseHost string) {
Вместо `MapStorage` лучше передавать интерфейс

2024-05-05 12:34 UTC, s-shpak commented on internal/app/middleware/middleware.go
> +		log.Println("Incoming request:", r.Method, r.URL.Path)
```suggestion
		log.Printf(...)
```

2024-05-05 12:34 UTC, s-shpak commented on internal/app/middleware/middleware_test.go
> +			if gotType := reflect.TypeOf(got); gotType != tt.want {
Зачем этот тест ? Какая разница, какой тип возвращается ? Эта проверка автоматически проводится компилятором

2024-05-05 12:34 UTC, s-shpak commented on internal/app/storage/storage/storage.go
> +type Repositories interface {
Зачем этот интерфейс ?

2024-05-05 12:34 UTC, s-shpak commented on internal/app/storage/mapstorage/mapstorage.go
> +		return errors.New("key already exists")
Кажется, что стоит попробовать несколько раз

2024-05-05 19:10 UTC, mmskazak commented on internal/pkg/shorturl/shorturl_test.go
> +	t.Skip()
Оставил, думал придумаю решение, тест проходит успушно, правда после запуска, сервер не остранавливатеся, попробую найти вариант остановить его наверное через defer

2024-05-05 19:12 UTC, mmskazak commented on internal/app/helpers/helpers.go
> +	"crypto/rand"
я по началу так и сделал, но у меня на него ругался какой то линтер

2024-05-05 20:04 UTC, mmskazak commented on internal/app/helpers/appinfo.go
> +func GetAppNameAndVersion() AppInfo {
вернул ошибку, если не полученна информация о приложении.

2024-05-06 07:31 UTC, mmskazak commented on cmd/shortener/main_test.go
> +func TestMainPage_Get_Greeting(t *testing.T) {
удалил файл main_test.go, по сути там все тесты дублировали handlers_test.go, просто написаны были раньше и чуть по другому, а так да одно и тоже было.

2024-05-06 07:31 UTC, mmskazak commented on cmd/shortener/main.go
> +const readTimeout = 10 * time.Second
убрал в config.go

2024-05-06 07:33 UTC, mmskazak commented on internal/app/config/config.go
> +type IConfig interface {
удалил его вообще, так как там были геттеры к структуре

2024-05-06 07:34 UTC, mmskazak commented on internal/app/config/config.go
> +	GetAddress() string
удалил этот интерфейс

2024-05-06 07:38 UTC, mmskazak commented on internal/app/config/config.go
> +	flag.StringVar(&config.address, "a", config.GetAddress(), "Устанавливаем ip адрес нашего сервера.")
flag.StringVar(&config.Address, "a", config.Address, "IP-адерс сервера")
	flag.StringVar(&config.BaseHost, "b", config.BaseHost, "Базовый URL")
	flag.DurationVar(&config.ReadTimeout, "r", config.ReadTimeout, "ReadTimeout duration")
	flag.DurationVar(&config.WriteTimeout, "w", config.WriteTimeout, "WriteTimeout duration")
поправил

2024-05-06 07:54 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +package shorturl
ну директория **internal/pkg** предназначена для использования только внутри моего проекта и не должна быть импортирована, это мои внутренние пакеты, выделил логику в отдельную утилиту(пакет), в main просто декларативно запускаю.

2024-05-06 07:55 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +package shorturl
ну директория **internal/pkg** предназначена для использования только внутри моего проекта и не должна быть импортирована, это мои внутренние пакеты, выделил логику в отдельную утилиту(пакет), в main просто декларативно запускаю.

2024-05-06 07:55 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +package shorturl
ну директория **internal/pkg** предназначена для использования только внутри моего проекта и не должна быть импортирована, это мои внутренние пакеты, выделил логику в отдельную утилиту(пакет), в main просто декларативно запускаю.

2024-05-06 08:06 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +	log.Println("Server is running on " + a.server.Addr)
`log.Printf("Server is running on %v", a.server.Addr)`
поправил

2024-05-06 08:08 UTC, mmskazak commented on internal/pkg/shorturl/shorturl_test.go
> +	t.Skip()
удалил пока эти тесты

2024-05-06 08:40 UTC, mmskazak commented on internal/app/handlers/handles.go
> +		return
```
err = data.SetShortURL(id, originalURL)
	if err != nil {
		errorGenerateShortURL := fmt.Errorf("ошибка формирования короткого url  %w", err)
		log.Printf("Ошибка SetShortURL: %v", errorGenerateShortURL)

		w.WriteHeader(http.StatusInternalServerError)
		_, err = w.Write([]byte("Сервису не удалось сформировать короткий URL"))
		if err != nil {
			log.Printf("Ошибка ответа ResponseWriter: %v ", err)
		}
	}
```
поменял на такой вариант

2024-05-06 08:40 UTC, mmskazak commented on internal/app/handlers/handles.go
> +		return
```
err = data.SetShortURL(id, originalURL)
	if err != nil {
		errorGenerateShortURL := fmt.Errorf("ошибка формирования короткого url  %w", err)
		log.Printf("Ошибка SetShortURL: %v", errorGenerateShortURL)

		w.WriteHeader(http.StatusInternalServerError)
		_, err = w.Write([]byte("Сервису не удалось сформировать короткий URL"))
		if err != nil {
			log.Printf("Ошибка ответа ResponseWriter: %v ", err)
		}
	}
```
поменял на такой вариант

2024-05-06 09:23 UTC, mmskazak commented on internal/app/handlers/handles.go
> +func CreateShortURL(w http.ResponseWriter, r *http.Request, data *mapstorage.MapStorage, baseHost string) {
заменил на интерфейс
```
type IStorage interface {
	GetShortURL(id string) (string, error)
	SetShortURL(id string, targetURL string) error
}
```

2024-05-06 09:23 UTC, mmskazak commented on internal/app/handlers/handles.go
> +func CreateShortURL(w http.ResponseWriter, r *http.Request, data *mapstorage.MapStorage, baseHost string) {
заменил на интерфейс
```
type IStorage interface {
	GetShortURL(id string) (string, error)
	SetShortURL(id string, targetURL string) error
}
```

2024-05-06 09:25 UTC, mmskazak commented on internal/app/middleware/middleware.go
> +		log.Println("Incoming request:", r.Method, r.URL.Path)
заменил
`log.Printf("Incoming request: %v %v", r.Method, r.URL.Path)`

2024-05-06 10:58 UTC, mmskazak commented on internal/app/middleware/middleware_test.go
> +			if gotType := reflect.TypeOf(got); gotType != tt.want {
удалили этот тест

2024-05-06 11:12 UTC, mmskazak commented on internal/app/storage/storage/storage.go
> +type Repositories interface {
удалил этот интерфейс и файл, создал новый интерфейс, там где он используется в handlers.go, ошибку перенес в mapstorage.go

2024-05-06 13:22 UTC, mmskazak commented on internal/app/storage/mapstorage/mapstorage.go
> +		return errors.New("key already exists")
сделал 10 попыток, но надо теперь подумать над тестированием

2024-05-06 13:30 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +		log.Println("Error starting server:", err)
изменил условие
`	if err != nil && !errors.Is(err, http.ErrServerClosed) {`

2024-05-06 13:57 UTC, mmskazak commented on internal/app/helpers/appinfo.go
> +	if app.name == "" {
ответ выше

2024-05-06 18:37 UTC, mmskazak commented on internal/pkg/shorturl/shorturl.go
> +	ms := mapstorage.NewMapStorage()
`func NewApp(cfg *config.Config, storage IStorage, readTimeout time.Duration, writeTimeout time.Duration) *App {`
теперь передаю извне, но пришлось второй раз объявить интерфейс.

2024-05-10 13:45 UTC, s-shpak requested changes
Добавь меня в контрибьютеры проекта, чтобы я мог резолвить комментарии

2024-05-10 13:45 UTC, s-shpak commented on .golangci.yml
> +    # For example: http://github.com/timonwong/loggercheck/blob/7395ab86595781e33f7afba27ad7b55e6956ebcd/testdata/custom-rules.txt
Что это ?

2024-05-10 13:45 UTC, s-shpak commented on internal/app/app.go
> +		log.Printf(ErrStartingServer+": %v", err)
```suggestion
		log.Printf("%v: %v", ErrStartingServer, err)
```

2024-05-10 13:45 UTC, s-shpak commented on internal/app/config/config_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
Лучше использовать https://pkg.go.dev/github.com/google/go-cmp/cmp#Equal

2024-05-10 13:45 UTC, s-shpak commented on internal/app/handlers/handles.go
> +	id, err := helpers.GenerateShortURL(defaultShortURLLength)
Перенеси это внутрь цикла (вызывай генерацию `GenerateShortURL` только внутри цикла)

2024-05-10 14:46 UTC, mmskazak commented on .golangci.yml
> +    # For example: http://github.com/timonwong/loggercheck/blob/7395ab86595781e33f7afba27ad7b55e6956ebcd/testdata/custom-rules.txt
случайно, замену сделал

2024-05-10 16:38 UTC, mmskazak commented on internal/app/config/config_test.go
> +			if !reflect.DeepEqual(got, tt.want) {
заменил
`if cmp.Equal(got, tt.want) {`

2024-05-10 16:39 UTC, mmskazak commented on internal/app/app.go
> +		log.Printf(ErrStartingServer+": %v", err)
Заменил
`log.Printf("%v: %v", ErrStartingServer, err)`

2024-05-10 16:40 UTC, mmskazak commented on .golangci.yml
> +    # For example: http://github.com/timonwong/loggercheck/blob/7395ab86595781e33f7afba27ad7b55e6956ebcd/testdata/custom-rules.txt
вернул
https://github.com/timonwong/loggercheck/blob/7395ab86595781e33f7afba27ad7b55e6956ebcd/testdata/custom-rules.txt

2024-05-10 17:08 UTC, mmskazak commented on internal/app/handlers/handles.go
> +	id, err := helpers.GenerateShortURL(defaultShortURLLength)
перенес
```
func saveUniqueShortURL(storage IStorage, originalURL string) (string, error) {
	for range maxIteration {
		id, err := helpers.GenerateShortURL(defaultShortURLLength)
		if err != nil {
			return "", fmt.Errorf("функция GenerateShortURL вернула ошибку %w", err)
		}

		err = storage.SetShortURL(id, originalURL)
		if err == nil {
			return id, nil
		} else {
			return "", fmt.Errorf("метод SetShortURL вернула ошибку %w", err)
		}
	}
	return "", errors.New("не удалось сгенерировать уникальный идентификатор")
}
```

2024-05-11 13:06 UTC, s-shpak requested changes

2024-05-11 13:06 UTC, s-shpak commented on internal/app/handlers/handles.go
> +		} else {
Этот `else` не нужен

2024-05-11 13:06 UTC, s-shpak commented on internal/app/handlers/handles.go
> +	defer func(Body io.ReadCloser) {
В серверном коде не обязательно закрывать тело запроса, он сделает это автоматически

2024-05-11 13:06 UTC, s-shpak commented on cmd/shortener/main.go
>  	cfg, errCfg := config.InitConfig()
Зачем довать новое имя ошибке здесь ?

2024-05-11 13:54 UTC, mmskazak commented on internal/app/handlers/handles.go
> +	defer func(Body io.ReadCloser) {
убрал, просто начитался, вроде говорилось что лучше закрыть, и да упоминалось что сервер в основном сам закрывает body

2024-05-11 14:00 UTC, mmskazak commented on cmd/shortener/main.go
>  	cfg, errCfg := config.InitConfig()
вернул, просто с таким же названием выше объявляется ошибка, но пересмотрел, понял что из инициализации конфига вернет новое значение nil или ошибку и запишет в эту переменную
```
	appInfo, err := helpers.GetAppNameAndVersion()
	if err != nil {
		log.Printf("Ошибка при получении информации о приложении: %v", err)
	} else {
		log.Printf("Название приложения: %v", appInfo.Name)
		log.Printf("Версия: %v", appInfo.Version)
	}

	cfg, err := config.InitConfig()
	if err != nil {
		log.Printf("ошибка инициализации конфигурации в main %v", err)
	}
```

2024-05-11 18:16 UTC, mmskazak commented on internal/app/handlers/handles.go
> +		} else {
```
err = storage.SetShortURL(id, originalURL)
if err == nil {
	eturn id, nil
} else {
         return "", fmt.Errorf("метод SetShortURL вернула ошибку %w", err)
}
```
эта конструкция с else по сути ошибка, которую я не протестировал, в случае колиизии была бы ошибка и эта конструкция сразу бы завершила цикл. Для того чтобы можно было протестировать этот случай я вынес генератор уникальных идентификаторов(я их именую короткими URL) в зависимость, чтобы можно было его мокнуть. Думаю потом переименную генератор уникальных идентификаторов.

2024-05-11 18:17 UTC, mmskazak commented on internal/app/handlers/handles.go
> +		} else {
функция теперь такая
```
func saveUniqueShortURL(storage IStorage, generator IGenShortURL, originalURL string) (string, error) {
	if originalURL == "" {
		return "", ErrOriginalURLIsEmpty
	}

	var err error
	for range maxIteration {
		id, err := generator.Generate(defaultShortURLLength)
		if err != nil {
			return "", fmt.Errorf("%w: %w", ErrFuncGenerate, err)
		}

		err = storage.SetShortURL(id, originalURL)
		if err == nil {
			return id, nil
		}
	}
	return "", fmt.Errorf("%w: %w", ErrMethodSetShortURLNotCanSave, err)
}
```

2024-05-12 06:59 UTC, s-shpak requested changes

2024-05-12 06:59 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Printf("ошибка инициализации конфигурации в main %v", err)
Сорри, я не обратил внимание: мы не можем продолжать выполнение программы после ошибки получения конфигурации

2024-05-12 09:26 UTC, mmskazak commented on cmd/shortener/main.go
> +		log.Printf("ошибка инициализации конфигурации в main %v", err)
заменил на log.Fatalf
```
	cfg, err := config.InitConfig()
	if err != nil {
		log.Fatalf("ошибка инициализации конфигурации в main %v", err)
	}

```

2024-05-12 10:52 UTC, s-shpak approved these changes

2024-05-13 09:50 UTC, merged