Iter9
mmskazak/shorturl pull request #9
Opened 2024-05-22 20:59 UTC by mmskazak

2024-05-25 11:48 UTC, s-shpak commented on internal/logger/output.go
> +var Log *zap.SugaredLogger
Не вижу смысла создавать глобальную переменную с логгером: лучше передавай инстанс логгера туда, где он нужен

2024-05-25 12:00 UTC, s-shpak requested changes

2024-05-25 12:00 UTC, s-shpak commented on internal/logger/output.go
> +var Log *zap.SugaredLogger
Не вижу смысла создавать глобальную переменную с логгером: лучше передавай инстанс логгера туда, где он нужен

2024-05-25 12:00 UTC, s-shpak commented on internal/logger/file.go
> +var Logf *zap.SugaredLogger
Не очень понимаю, зачем тебе логгер, который пишет что-то в файл: обычно сервис пишет логи либо в stdout, либо в системный журнал

2024-05-25 12:00 UTC, s-shpak commented on internal/storage/mapstorage/mapstorage.go
> +func NewMapStorage(filePath string) *MapStorage {
Хотелось бы, чтобы:

1. Существовала функция, из которой возвращался бы объект общего интерфейса
2. Существовало две имплементации харинилища - in-memory и файловая
3. Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции

2024-05-25 12:00 UTC, s-shpak commented on cmd/shortener/main.go
> +func readFileStorage(consumer *rwstorage.Consumer, ms *mapstorage.MapStorage, logf *zap.SugaredLogger) error {
Почему это лежит в пакете `main`, а не там, где создается хендлер к хранилищу ?

2024-05-25 12:00 UTC, s-shpak commented on internal/handlers/api/api.go
> +type IStorage interface {
В го непринято, в основном, давать интрефейсам префиксы `I`

```suggestion
type Storage interface {
```

2024-05-25 12:00 UTC, s-shpak commented on internal/middleware/logging.go
> +			"status", responseData.status, // получаем перехваченный код статуса ответа
А что если `WriteHeader` не будет вызван ? Какой статус-код залогируется ?

2024-05-25 12:00 UTC, s-shpak commented on internal/handlers/web/web.go
> +type IStorage interface {
См. коммент про имена интерфейсов

2024-05-25 16:56 UTC, mmskazak commented on internal/handlers/web/web.go
> +type IStorage interface {
Переименовал

2024-05-25 16:56 UTC, mmskazak commented on internal/handlers/api/api.go
> +type IStorage interface {
Переименовал

2024-05-25 19:28 UTC, mmskazak commented on internal/logger/output.go
> +var Log *zap.SugaredLogger
Удалил, передаю туда где от нужен.

2024-05-25 19:29 UTC, mmskazak commented on internal/logger/file.go
> +var Logf *zap.SugaredLogger
Удалил

2024-05-25 19:55 UTC, mmskazak commented on internal/middleware/logging.go
> +			"status", responseData.status, // получаем перехваченный код статуса ответа
// If [ResponseWriter.WriteHeader] has not yet been called, Write calls
	// WriteHeader(http.StatusOK) before writing the data.

2024-05-25 19:58 UTC, mmskazak commented on internal/middleware/logging.go
> +			"status", responseData.status, // получаем перехваченный код статуса ответа
func (r *loggingResponseWriter) Write(b []byte) (int, error) {
	// записываем ответ, используя оригинальный http.ResponseWriter
	size, err := r.ResponseWriter.Write(b)
	if err != nil {
		return 0, fmt.Errorf("ошибка в middleware.loggingResponseWriter.Write %w", err)
	}
	r.responseData.size += size // захватываем размер
	r.responseData.status = http.StatusOK
	return size, nil
}

func (r *loggingResponseWriter) WriteHeader(statusCode int) {
	// записываем код статуса, используя оригинальный http.ResponseWriter
	r.ResponseWriter.WriteHeader(statusCode)
	r.responseData.status = statusCode // захватываем код статуса
}

2024-05-25 20:56 UTC, mmskazak commented on cmd/shortener/main.go
> +func readFileStorage(consumer *rwstorage.Consumer, ms *mapstorage.MapStorage, logf *zap.SugaredLogger) error {
переместил в новый билдер, который как создает мапу так и наполняет ее данными
`ms, err = mapstorage.NewMapStorageWithData(pathToStorage, consumer, zapLog)`

2024-05-26 17:49 UTC, mmskazak commented on internal/storage/mapstorage/mapstorage.go
> +func NewMapStorage(filePath string) *MapStorage {
создал фабрику, в ней две имплементации интерфейса Storage
```
type Storage interface {
	GetShortURL(id string) (string, error)
	SetShortURL(id string, targetURL string) error
}

func NewStorage(storageType string, cfg *config.Config) (Storage, error) {
	switch storageType {
	case "inmemory":
		return inmemory.NewInMemory() //nolint:wrapcheck //ошибка обрабатывается далее
	case "infile":
		return infile.NewInFile(cfg) //nolint:wrapcheck //ошибка обрабатываетсяч далее
	default:
		return nil, fmt.Errorf("unknown storage type: %s", storageType)
	}
}

```
Реализовал композицию
```
type InFile struct {
	InMe     *inmemory.InMemory
	FilePath string
}

func (m *InFile) GetShortURL(id string) (string, error) {
	return m.InMe.GetShortURL(id) //nolint:wrapcheck //ошибка обрабатывается далее
}
```

2024-05-28 07:23 UTC, s-shpak requested changes

2024-05-28 07:23 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatalf("Ошибка инициализации хранилища: %v", err)
Здесь ты уже можешь использовать `zapLog`

2024-05-28 07:23 UTC, s-shpak commented on internal/handlers/web/web_test.go
> +			ms, _ := inmemory.NewInMemory()
Ошибки надо проверять и в тестах

2024-05-28 07:23 UTC, s-shpak commented on internal/storage/storage.go
> +		return inmemory.NewInMemory() //nolint:wrapcheck //ошибка обрабатывается далее
Здесь к ошибке можно добавить контекст:


```suggestion
		s, err := inmemory.NewInMemory()
        if err != nil {
            return nil, fmt.Errorf("failed to initialize an in-memory store: %w", err)
        }
```

2024-05-28 07:23 UTC, s-shpak commented on internal/storage/inmemory/inmemory.go
> +	Mu   *sync.Mutex
Это поле не должно быть эскмортируемым (как и другие поля этой функции)

2024-05-28 07:23 UTC, s-shpak commented on internal/storage/inmemory/inmemory.go
> +var ErrNotFound = errors.New("key not found")
Эта ошибка может возвращаться и `file-store`, значит  ее надо объявить в более общем пакете

2024-05-28 07:23 UTC, s-shpak commented on internal/storage/infile/infile.go
> +	InMe     *inmemory.InMemory
Аналогично, эти поля не надо экспортировать

2024-05-28 07:23 UTC, s-shpak commented on internal/services/rwstorage/rwstorage.go
> +	data, err := c.reader.ReadBytes('\n')
Лучше реализовать это через `bufio.Scanner`

2024-05-28 07:23 UTC, s-shpak commented on internal/middleware/logging.go
> +func (r *loggingResponseWriter) Header() http.Header {
Если встроить `ResponseWriter` через композицию, то этот метод не надо будет переопределять

2024-05-28 07:23 UTC, s-shpak commented on internal/middleware/gzip.go
> +	Writer io.Writer
Обрати внимание: лучше всего по умолчанию делать поля структур неэкспортируемыми и экспортировать их только если это действительно необходимо

2024-05-28 07:23 UTC, s-shpak commented on internal/middleware/gzip.go
> +		} else {
`else` не нужен

2024-05-28 07:47 UTC, mmskazak commented on internal/handlers/web/web_test.go
> +			ms, _ := inmemory.NewInMemory()
```
ms, err := inmemory.NewInMemory()
require.NoError(t, err)
```

2024-05-28 08:07 UTC, mmskazak commented on internal/storage/storage.go
> +		return inmemory.NewInMemory() //nolint:wrapcheck //ошибка обрабатывается далее
```
	sm, err := inmemory.NewInMemory()
		if err != nil {
			return nil, fmt.Errorf("failed to initialize an in-memory store: %w", err)
		}
        return sm, nil
```

2024-05-28 08:24 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +	Mu   *sync.Mutex
```
	return &InMemory{
		mu:   &sync.Mutex{},
```
Data оставил экспортируемым, пока не понятно как его сделать не экспортируемым

2024-05-28 08:27 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +var ErrNotFound = errors.New("key not found")
`var ErrNotFound = errors.New("key not found")`
переместил в storage.go

2024-05-28 09:56 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +var ErrNotFound = errors.New("key not found")
Вернул обратно, если выношу в storage.go то получаются циклическая зависимость.

2024-05-28 09:57 UTC, mmskazak commented on internal/storage/infile/infile.go
> +	InMe     *inmemory.InMemory
```
	ms := &InFile{
		inMe:     inm,
```

2024-05-28 10:10 UTC, mmskazak commented on internal/middleware/gzip.go
> +	Writer io.Writer
```
type GzipResponseWriter struct {
	writer io.Writer
```

2024-05-28 10:15 UTC, mmskazak commented on internal/middleware/gzip.go
> +		} else {
```
		gzipResponseWriter := &GzipResponseWriter{writer: gzipWriter, ResponseWriter: w}
			next.ServeHTTP(gzipResponseWriter, r)
			return
		}
		next.ServeHTTP(w, r)
```

2024-05-28 10:31 UTC, mmskazak commented on internal/middleware/logging.go
> +func (r *loggingResponseWriter) Header() http.Header {
```
type loggingResponseWriter struct {
	http.ResponseWriter // встраиваем оригинальный http.ResponseWriter
	responseData        *responseData
}

func (r *loggingResponseWriter) Write(b []byte) (int, error) {
	// записываем ответ, используя оригинальный http.ResponseWriter
	size, err := r.ResponseWriter.Write(b)
	if err != nil {
		return 0, fmt.Errorf("ошибка в middleware.loggingResponseWriter.Write %w", err)
	}
	r.responseData.size += size // захватываем размер
	if r.responseData.status == noStatus {
		r.responseData.status = http.StatusOK
	}
	return size, nil
}

func (r *loggingResponseWriter) WriteHeader(statusCode int) {
	// записываем код статуса, используя оригинальный http.ResponseWriter
	r.ResponseWriter.WriteHeader(statusCode)
	r.responseData.status = statusCode // захватываем код статуса
}
```

2024-05-28 10:40 UTC, mmskazak commented on cmd/shortener/main.go
> +		log.Fatalf("Ошибка инициализации хранилища: %v", err)
ms, err := storage.NewStorage(cfg)
	if err != nil {
		zapLog.Fatalf("Ошибка инициализации хранилища: %v", err)
	}

2024-05-28 11:20 UTC, mmskazak commented on internal/services/rwstorage/rwstorage.go
> +	data, err := c.reader.ReadBytes('\n')
```
func (c *Consumer) ReadLineInFile() (*ShortURLStruct, error) {
	// читаем данные до символа переноса строки
	data := c.Reader.Text()
```

2024-05-28 12:24 UTC, s-shpak commented on internal/storage/inmemory/inmemory.go
> +var ErrNotFound = errors.New("key not found")
В этом случае объяви это в отдельном пакете, но на уровне `Storage`

2024-05-28 12:26 UTC, s-shpak requested changes
См. последний комментарий

2024-05-28 18:03 UTC, mmskazak commented on internal/storage/inmemory/inmemory.go
> +var ErrNotFound = errors.New("key not found")
перенес общие ошибки в пакет common

2024-05-29 09:50 UTC, s-shpak requested changes

2024-05-29 09:50 UTC, s-shpak commented on internal/common/errors.go
> +package common
Это плохая практика:
1. пакеты `common`, `util` и т.п. считаются плохой практикой, потому что туда можо положить что угодно, а, с другой стороны, неясно, что там находится
2. сущности лучше размещать там, где они используются. Т.к. эти ошибки относятся к хранилищу, лучше положить их, например, в пакет `storage/errors`

2024-05-29 18:47 UTC, mmskazak commented on internal/common/errors.go
> +package common
перенес в `storage/errors`

2024-05-29 18:55 UTC, s-shpak approved these changes

2024-05-30 06:12 UTC, merged